version: "3.9"

services:
  seed:
    build:
      context: ..                 # repo root
      dockerfile: labs/Dockerfile
    container_name: kad-seed
    command: ["seed"]            # <-- only the role, ENTRYPOINT already runs the script
    environment:
      PORT: "9000"
    networks: [kadnet]
    stdin_open: true             # needed for docker attach
    tty: true                    # needed for docker attach
    restart: unless-stopped

  knode:
    build:
      context: ..
      dockerfile: labs/Dockerfile
    command: ["node"]            # <-- only the role
    depends_on: [seed]
    environment:
      PORT: "9000"
      BOOTSTRAP_HOST: "seed"
    networks: [kadnet]
    stdin_open: true  # needed for docker attach
    tty: true # needed for docker attach
    restart: unless-stopped

networks:
  kadnet:
    driver: bridge
