services:
  seed:
    build:
      context: ..              # repo root (has labs/)
      dockerfile: labs/Dockerfile
    image: d7024e-node:latest
    command: ["seed"]         # passed to entrypoint.sh
    environment:
      PORT: "9000"
    networks: [kadnet]
    expose: ["9000/udp"]
    stdin_open: true
    tty: true
    restart: unless-stopped

  knode:
    build:
      context: ..
    # uses the same labs/Dockerfile by default since it's in the context root? No—be explicit:
      dockerfile: labs/Dockerfile
    image: d7024e-node:latest
    command: ["node"]
    depends_on: [seed]
    environment:
      PORT: "9000"
      BOOTSTRAP_HOST: "seed"
    networks: [kadnet]
    expose: ["9000/udp"]
    restart: unless-stopped

networks:
  kadnet:
    driver: bridge
